apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.serviceName }}
  description: ${{ values.description }}
  annotations:
    github.com/project-slug: YOUR_GITHUB_ORG/${{ values.serviceName }}
    backstage.io/kubernetes-id: ${{ values.serviceName }}
spec:
  type: service
  lifecycle: experimental
  owner: ${{ values.owner }}
  system: internal-developer-platform
